import type { Category, Listing } from './supabase';

export const mockCategories: Category[] = [
  { id: 'mock-cat-engineering', name: 'Engineering', slug: 'engineering', icon: 'code-2' },
  { id: 'mock-cat-design', name: 'Design', slug: 'design', icon: 'palette' },
  { id: 'mock-cat-marketing', name: 'Marketing', slug: 'marketing', icon: 'megaphone' },
  { id: 'mock-cat-trade', name: 'Skilled Trade', slug: 'skilled-trade', icon: 'hammer' },
];

export const mockListings: Listing[] = [
  {
    id: 'mock-listing-frontend',
    company_id: 'mock-company-northstar',
    title: 'Frontend Engineer, Marketplace Tools',
    description: 'Build polished React interfaces for scheduling, application tracking, and company dashboards. You will work across design systems, Supabase data flows, and high-trust user journeys where clarity matters.',
    category_id: 'mock-cat-engineering',
    location: 'Remote, South Africa',
    employment_type: 'full-time',
    salary_range: 'R720k - R980k',
    status: 'open',
    created_at: new Date().toISOString(),
    categories: mockCategories[0],
    companies: {
      org_name: 'Northstar Works',
      description: 'A small product studio building tools for modern hiring teams.',
      logo_url: null,
      is_verified: true,
      website: 'https://example.com',
    },
  },
  {
    id: 'mock-listing-brand',
    company_id: 'mock-company-cinder',
    title: 'Brand Designer for Opportunity Platform',
    description: 'Create visual systems, listing templates, and campaign assets for a growing services marketplace. Strong typography, restraint, and product thinking are more important than trend-chasing.',
    category_id: 'mock-cat-design',
    location: 'Cape Town Hybrid',
    employment_type: 'contract',
    salary_range: 'R45k - R65k / month',
    status: 'open',
    created_at: new Date().toISOString(),
    categories: mockCategories[1],
    companies: {
      org_name: 'Cinder & Co.',
      description: 'Brand and experience team for early-stage companies.',
      logo_url: null,
      is_verified: false,
      website: null,
    },
  },
  {
    id: 'mock-listing-growth',
    company_id: 'mock-company-stepwise',
    title: 'Growth Marketing Coordinator',
    description: 'Coordinate experiments across email, content, partnerships, and local events. You will turn messy signals into practical campaigns and report on what actually creates applications.',
    category_id: 'mock-cat-marketing',
    location: 'Johannesburg',
    employment_type: 'part-time',
    salary_range: 'R280 - R420 / hour',
    status: 'open',
    created_at: new Date().toISOString(),
    categories: mockCategories[2],
    companies: {
      org_name: 'Stepwise Careers',
      description: 'Career mobility programs for first-time job seekers.',
      logo_url: null,
      is_verified: true,
      website: 'https://example.com',
    },
  },
  {
    id: 'mock-listing-solar',
    company_id: 'mock-company-brightline',
    title: 'Solar Installation Apprentice',
    description: 'Join a field team installing residential solar systems. Ideal for someone reliable, practical, and ready to learn electrical safety, site prep, and customer handover basics.',
    category_id: 'mock-cat-trade',
    location: 'Durban',
    employment_type: 'full-time',
    salary_range: 'R12k - R18k / month',
    status: 'open',
    created_at: new Date().toISOString(),
    categories: mockCategories[3],
    companies: {
      org_name: 'Brightline Energy',
      description: 'Regional solar installer focused on training new technicians.',
      logo_url: null,
      is_verified: false,
      website: null,
    },
  },
];